hw10_program_optimization
ar2r/go-otus pull request #11
Opened 2024-10-11 16:28 UTC by ar2r

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-10-11 17:46 UTC, vladislavmass requested changes

2024-10-11 17:46 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +	if strings.Contains(email, domain) {
Это условие также сработает если у меня будет email xyz.com@mail.ru и я буду делать статистику по домену com.  Смотрите в сторону HasPrefix

2024-10-11 17:46 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +		return strings.SplitN(strings.ToLower(email), "@", 2)[1]
Если вдруг во входном наборе не будет символа собаки то мы тут получим панику

2024-10-11 17:46 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  type User struct {
Нам точно нужны все поля этой структуры?

2024-10-11 19:24 UTC, ar2r commented on hw10_program_optimization/stats.go
>  type User struct {
Я убирал из этой структуры лишние поля, но это практически не дало прироста производительности. Поэтому ради копеечного прироста производительности не стал удалять.
Ок, удалю лишние поля.

2024-10-11 19:24 UTC, ar2r commented on hw10_program_optimization/stats.go
> +		return strings.SplitN(strings.ToLower(email), "@", 2)[1]
Дополнил тестовые данные, добавил проверку этого кейса.

2024-10-11 19:24 UTC, ar2r commented on hw10_program_optimization/stats.go
> +	if strings.Contains(email, domain) {
Отличное замечание, которое я не учел!

2024-10-12 04:00 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  type User struct {
Вообще плохая идея в принципе делать поля которые не используются. Как минимум это увеличивает кодовую базу, как максимум если мы поменяем текущий json маршлер на другой то там уже лишние поля могут негативно сказаться на скорости обработки

2024-10-12 04:07 UTC, vladislavmass approved these changes

2024-10-12 18:12 UTC, merged