hw11_telnet_client
ar2r/go-otus pull request #12
Opened 2024-10-26 14:09 UTC by ar2r

## Домашнее задание №11 «Клиент TELNET»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2024-10-26 14:13 UTC, ar2r commented
На MacBook вот такой запуск не работает `nc -l localhost 4242`

Пришлось локально test.sh исправить и прописать `nc -l -p 4242 localhost`

2024-10-26 14:54 UTC, vladislavmass requested changes

2024-10-26 14:54 UTC, vladislavmass commented on hw11_telnet_client/telnet.go
> +	if errors.Is(err, io.EOF) {
Поясните пожалуйста логику строк с 46 по 51.  Чем это будет отличаться от ситуации если оставить только строки с 49 по 51?

2024-10-26 14:54 UTC, vladislavmass commented on hw11_telnet_client/telnet.go
> +	return client.connection.Close()
А если у нас connection==nil то это прямой путь к панике, хотя должна быть ошибка

2024-10-26 14:54 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +	defer cancel()
В чем логика этой строки, если пока не произойдет cancel то ctx.Done ничего не получит?

2024-10-26 16:31 UTC, ar2r commented on hw11_telnet_client/telnet.go
> +	if errors.Is(err, io.EOF) {
В задании написано, что нужно перехватывать CTRL+D. Этот сигнал конца ввода можно отловить через проверку на EOF.

2024-10-26 16:34 UTC, vladislavmass commented on hw11_telnet_client/telnet.go
> +	if errors.Is(err, io.EOF) {
А разве этот кейс не отработает если оставить только `if err!=nil`? Поведение ведь одно и тоже

2024-10-26 17:06 UTC, ar2r commented on hw11_telnet_client/main.go
> +	defer cancel()
**Выглядит бессмысленно. Точно подмечено.**

Контекст отменится (ctx.Done получит сигнал) в случае:
- при получении одного из сигналов: SIGINT или SIGTERM
- завершилась горутина с методом client.Send()
- завершилась горутина с методом client.Receive()

defer cancel() должен был запуститься когда функция main завершена, а в тот момент контекст уже 100% будет отменен.

2024-10-26 17:21 UTC, ar2r commented on hw11_telnet_client/main.go
> +	defer cancel()
Контекст может быть отменен при получении указанных сигналов (SIGINT, SIGTERM), но это не приведет к вызову cancel(), поэтому необходимо cancel() вызвать вручную.

А вот при вызове cancel() у меня не было реализовано завершение двух горутин. Это я добавил.

2024-10-26 17:25 UTC, ar2r commented on hw11_telnet_client/telnet.go
> +	return client.connection.Close()
Добавил проверку наличия соединения.

2024-10-26 17:29 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +	defer cancel()
А если посмотреть как устроен этот самый контекст, то увидим что дернет. Вся разница между сигналом и cancel в том, что по cancel мы " отпишемся" от хэндлеров сигналов системы

2024-10-26 17:34 UTC, ar2r commented on hw11_telnet_client/main.go
> +	defer cancel()
Действительно. Вызовется. Значит смело удаляю.

![image](https://github.com/user-attachments/assets/2618b4f5-da7a-4052-86f3-0602824ce2a7)

2024-10-26 17:35 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +		case <-ctx.Done():
А в чем тут смысл от этого `case <-ctx.Done():`? Если ниже в цикле я еще понимаю на что он рассчитан, то тут нет.  Условно программа запустилась, запустила обе рутины, за считаные такты мы проскакиваем этот обработчик и больше никогда с ним не встречаемся

2024-10-26 17:35 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +	defer cancel()
Да, именно так.

2024-10-26 17:46 UTC, vladislavmass requested changes

2024-10-26 17:46 UTC, vladislavmass commented on hw11_telnet_client/telnet.go
> +	buffer := make([]byte, 1024)
Telnet это диалоговый протокол, который подразумевает вопрос ответ. А тут мы получаем ситуацию когда мы один раз читаем и пишем в канал и на этом все. Тоесть ответить мы уже не можем

2024-10-26 19:13 UTC, ar2r commented on hw11_telnet_client/telnet.go
> +	buffer := make([]byte, 1024)
Диалоговый режим стал работать, после исправления - добавил `for` + `select` в функции `Send`, `Receive`.

![Запись-экрана-2024-10-26-в-21 47 13](https://github.com/user-attachments/assets/4547a88c-ef59-434c-b63d-4a86611ded36)

2024-10-26 19:20 UTC, ar2r commented on hw11_telnet_client/main.go
> +		case <-ctx.Done():
`ctx` решил пробрасывать внутрь клиента.

2024-10-26 19:24 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +		case <-ctx.Done():
Менять изначальные сигнатуры функций и интерфейсы нельзя

2024-10-26 20:57 UTC, vladislavmass commented on hw11_telnet_client/main.go
> +					log.Fatalln(err)
Очень странно на данный момент выглядит этот блок. Если пришел ctx.Done то звать cancel смысла нет, а в случае ошибки в методе Send log.Fatal прибьет весь процесс через os.Exit(1)

2024-10-27 12:00 UTC, ar2r commented on hw11_telnet_client/main.go
> +					log.Fatalln(err)
Отправил ошибки в os.Stderr и завершил горутину через return.

2024-10-27 12:37 UTC, vladislavmass approved these changes

2024-10-27 12:48 UTC, merged