Утилита для копирования файлов
ar2r/go-otus pull request #8
Opened 2024-09-21 13:41 UTC by ar2r

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-09-21 19:26 UTC, vladislavmass requested changes
Хорошее начало, эта утилита подойдет под копирование мелких файлов, но копировать через нее большие файлы очень плохая идея. Предлагаю все таки рассмотреть использование библиотек и копирование через io.Copy

2024-09-21 19:26 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		if err != nil {
В целом в данном случае никто ошибки обычно не обрабатывает, да и в целом ошибки закрытия файлов очень большая редкость)

2024-09-21 19:26 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	if limit < maxFileSizeWithoutProgressBar {
Нарушение тз. Прогрессивные бар должен быть всегда

2024-09-21 19:26 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	toFile, err := os.Create(toPath)
Что будет если входной и выходной путь совпадут?

2024-09-21 19:26 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	if fileInfo.Size() == 0 {
Копирование пустого файла вполне себе нормальная ситуацию и никак не связан с поддерживаемым типом

2024-09-21 19:26 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	copyBufferSize           = 42
Не очень хорошая идея. Подумайте сколько нужно сделать подходов что бы по 42 байта скопировать фильм весом в 60 гигабайт

2024-09-21 19:26 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		printProgress(copied, limit)
Современный ssd способен копировать со скоростью более 2 гигабайт в секунду. Консоль работает значительно медленнее и она может стать тут узким местом

2024-09-21 20:44 UTC, ar2r commented on hw07_file_copying/copy.go
> +	toFile, err := os.Create(toPath)
При совпадении происходила очистка файла.
Добавил сравнение файлов через inode.

2024-09-21 20:45 UTC, ar2r commented on hw07_file_copying/copy.go
> +	if fileInfo.Size() == 0 {
Убрал эту проверку.

2024-09-21 20:45 UTC, ar2r commented on hw07_file_copying/copy.go
> +	copyBufferSize           = 42
Изучив информацию из интернета - оптимальное значение это 32Кб.

2024-09-21 20:46 UTC, ar2r commented on hw07_file_copying/copy.go
> +		printProgress(copied, limit)
Прогресс бар теперь рефрешится не чаще 1 раза в секунду.

2024-09-21 20:53 UTC, ar2r commented on hw07_file_copying/copy.go
> +	if limit < maxFileSizeWithoutProgressBar {
Исправил.

2024-09-21 20:54 UTC, ar2r commented on hw07_file_copying/copy.go
> +		if err != nil {
IDE ругалась, поэтому решил добавить проверку, но когда писать код тоже были мысли, что делаю что-то бесполезное.

2024-09-22 06:50 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	toFile, err := os.Create(toPath)
В идеале хотелось конечно что бы это работало. Например захотим обрезать первые 100 байт например

2024-09-22 07:32 UTC, vladislavmass requested changes
Работа стала сильно лучше, но не корректное обрабатываются источники с неизвестной длинны. например /dev/urandom

2024-09-22 07:32 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		return ErrUnsupportedFile
Лучше под это ситуация создать отдельную ошибку

2024-09-22 07:32 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		return ErrUnsupportedFile
Лучше под это ситуация создать отдельную ошибку

2024-09-22 09:35 UTC, ar2r commented on hw07_file_copying/copy.go
> +	toFile, err := os.Create(toPath)
Добавил возможность писать и читать в одинаковый файл через промежуточный прокси файл.

2024-09-22 09:36 UTC, ar2r commented on hw07_file_copying/copy.go
> +		return ErrUnsupportedFile
Тут теперь логика для обработки ситуации когда fromPath === toPath. Ошибки в этом случае не будет.

2024-09-22 09:37 UTC, ar2r commented on hw07_file_copying/copy.go
> +		return ErrUnsupportedFile
Сделал.

2024-09-22 09:37 UTC, ar2r commented
Добавил обработку случаев типа /dev/urandom, когда нет возможность двигать указатель.

2024-09-22 10:54 UTC, vladislavmass requested changes

2024-09-22 10:54 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	if fromFileInfo.Size() == 0 && !fromFileInfo.Mode().IsRegular() {
На самом деле хватило бы и !fromFileInfo.Mode().IsRegular()

2024-09-22 10:54 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		defer func(tempToPath string, originalToPath string) {
На самом деле это делает только хуже. os.rename имеет ряд ограничения, Например такое что он работает только в рамках одного логического диска. Если у нас системная темп папка на диске C а копировать мы будем файл на диске D то мы просто потеряем пользовательские данные

2024-09-22 10:54 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		return err
Было бы круто еще удалять целевой файл в случае ошибки копирования

2024-09-22 10:54 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +			os.Remove(originalToPath)
Тут ошибки, которые стоит вывести.

2024-09-22 11:19 UTC, ar2r commented on hw07_file_copying/copy.go
> +			os.Remove(originalToPath)
os.Remove в итоге оказался не нужен, т.к. os.Create под капотом транкейтит файл.

2024-09-23 17:40 UTC, vladislavmass requested changes
2 копирование за место 2 точно не лучшее решение. А почему не хотите создать временный файл в директории с целевым файлом и потом использовать ренейм. Хэш файла и unixtime дадут достаточно уникальное имя. Либо можно вернутся к варианту с ошибкой если пути совпадают

2024-09-24 04:40 UTC, vladislavmass approved these changes

2024-09-24 04:40 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +			os.Remove(toPath)
В целом может быть и допустимо, но скорее всего тут будет таже ошибка что и при переименование.

2024-09-24 04:40 UTC, vladislavmass commented on hw07_file_copying/copy_test.go
> +			title:         "Ошибка чтения файла неизвестной длины (не поддерживает смещение)",
Платформозависемые тесты ужасная практика. В данном случае мы по сути закладываемся на то, что что в os есть /dev/urandom.

2024-09-24 04:40 UTC, vladislavmass commented on hw07_file_copying/copy_test.go
> +		{
В данном случае мы апелируем папкой за пределами нашей директории. Поэтому эта среда которую мы не контролируем. И получается что тут может быть далеко не 1 ошибка, например этой папки может не быть, или у нас нет прав доступа

2024-09-28 08:31 UTC, merged